### ISSUE TITLE
Incorrect migration scripts - wants to drop and re-create tables and does it in the wrong order

### ISSUE THREAD

**Issue by ssteiner** [dotnet/ef6#1388]
I've encountered this issue a bunch of times now. I'm using EF 6.2.0 with automatic migrations. Most of the time, all is well. Every now and then though, EF runs amock. I then get an exception telling me that table XY cannot be created because it already exists.

If I create a coded migration at this point, I see what EF tries to do:

First it drops any FK that might be on that table it doesn't like. Then It does a CreateTable for the same table. And at the end of the migration, it adds a DropTable.

Here's an example... touching the standard ASP.NET Identity tables our DB contains

    DropForeignKey("dbo.AspNetUserRoles", "RoleId", "dbo.AspNetRoles");
    
                CreateTable(
                "dbo.AspNetUserRoles",
                c => new
                {
                    RoleId = c.String(nullable: false, maxLength: 128),
                    UserId = c.String(nullable: false, maxLength: 128),
                })
                .PrimaryKey(t => new { t.RoleId, t.UserId })
                .ForeignKey("dbo.AspNetRoles", t => t.RoleId, cascadeDelete: true)
                .ForeignKey("dbo.AspNetUsers", t => t.UserId, cascadeDelete: true);

    DropTable("dbo.AspNetUserRoles");

So, the order is obviously wrong. If there's an FK to be dropped, the table is already there and you can't run CreateTable for the same table name. And, CreateTable followed by DropTable is resulting in nothing getting changed as well (if there were no table to begin with).

So, two issues here: 1: why does it want to drop a table and re-create the very same table. And 2: why does it do things in the wrong order.

I'm on Win10, VS 2017 15.9.17 (also happens in VS 2019 16.3.5), with SQL Server 2017.

I'm afraid I have no repro project because the mere split out DBL project already is comprised of a dozen libs.

**Comment by MJMontufar** [comment]
Hi guys, I have the same problems, over and over... with migrations and I have to check every time I make a Migration... check the following code.

` public partial class DeleteNavigationPropertyInVendorModelPurchaseInvoice : DbMigration
    {
        public override void Up()
        {
   (1st) Look =>  DropForeignKey("dbo.PurchaseInvoices", "Vendor_VendorId", "dbo.Vendors");
                           DropForeignKey("dbo.PurchaseDetails", "PurchaseDetailId", "dbo.PurchaseInvoices");
                           DropIndex("dbo.PurchaseInvoices", new[] { "Vendor_VendorId" });
   (2nd) Look => DropColumn("dbo.PurchaseDetails", "InvoicePurchaseId");
   (2nd) Look => RenameColumn(table: "dbo.PurchaseDetails", name: "PurchaseDetailId", newName: "InvoicePurchaseId");
                           RenameIndex(table: "dbo.PurchaseDetails", name: "IX_PurchaseDetailId", newName: "IX_InvoicePurchaseId");
    (3rd) Look => CreateIndex("dbo.PurchaseDetails", "PurchaseDetailId");
                           AddForeignKey("dbo.PurchaseDetails", "InvoicePurchaseId", "dbo.PurchaseInvoices", "InvoicePurchaseId", cascadeDelete: true);
                           DropColumn("dbo.PurchaseInvoices", "Vendor_VendorId");
        }
        
`
Notes:
1st. in the first DropForeingKey there is not a Vendor_VendorId property in the Vendor's Model neither in the SQL2017 DB.

2nd. the migration Drop the InvoicePurchaseId in the table dbo.PurchaseDetails, next Rename the column's table ID PurchaseDetailId with the column that Drop before...  it can't be possible and the SQL2017 reject the change, because PurchaseDetailId is the table's PrimaryKey and more columns depend on it.

3rd. Tried to create an Index with a column that suppose the name has been changed in the statement before, if the change were made, there is no column with the name PurchaseDetailId

4th. tried to DropColumn (Vendor_VendorId) that not exist in the Model and the SQL DB.

Can you tell us what happened @ajcvickers 
Thank you so much with your help guys, congrats, good job!!!

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
