### ISSUE TITLE
Migration cannot be used with version 6.3 of EntityFramework

### ISSUE THREAD

**Issue by CeciAc** [dotnet/ef6#1505]
Hi team,
I moved this from here: MicrosoftDocs/Contribute.ja-JP#10
@kantoexp commented 18 hours ago — with docs.microsoft.com
Migration does not work with version 6.3 of EntityFramework. Please improve it
as soon as possible.

Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

    ID: 70fbb1c8-1435-e762-8824-78cf96faed84
    Version Independent ID: 062879b5-72cf-2353-63f2-d862fe1b40ba
    Content: Microsoft Docs contributor guide overview - Contributor Guide
    Content Source: Contribute/index.md
    Product: non-product-specific
    GitHub Login: @BillWagner
    Microsoft Alias: wiwagn

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
