### ISSUE TITLE
Can not resolve reference: `System.Web`, referenced by

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/ef6#1506]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/839068/can-not-resolve-reference-systemweb-referenced-by.html)._

---
[regression] [worked-in:vs2017]
Since I upgraded to VS2019, my android project is failing on the following errors listed below.  If I unload the android project its all fine. 

Severity	Code	Description	Project	File	Line	Suppression State	Suppression State
Error		Can not resolve reference: `System.Web`, referenced by `MobileApp.Shared` > `SSW. Api.PublicInterface` > `SSW.Api.Common` > `EntityFramework` > `SSW. Cache` > `Castle.Windsor` > `Castle.Core`. Please add a NuGet package or assembly reference for `System.Web`, or remove the reference to `MobileApp.Shared`.	MobileApp.Android.SSW	

Severity	Code	Description	Project	File	Line	Suppression State	Suppression State
Error		Can not resolve reference: `System.Runtime.Caching`, referenced by `MobileApp.Shared` > `SSW. Api.PublicInterface` > `SSW.Api.Common` > `EntityFramework` > `SSW. Cache` > `Castle.Windsor` > `Castle.Core`. Please add a NuGet package or assembly reference for `System.Runtime.Caching`, or remove the reference to `MobileApp.Shared`.	MobileApp.Android.CAM				
			
Severity	Code	Description	Project	File	Line	Suppression State	Suppression State
Error		Can not resolve reference: `System.Configuration`, referenced by `MobileApp.Shared` > `SSW. Api.PublicInterface` > `SSW.Api.Common` > `EntityFramework` > `SSW. Cache` > `Castle.Windsor` > `Castle.Core`. Please add a NuGet package or assembly reference for `System.Configuration`, or remove the reference to `MobileApp.Shared`.	MobileApp.Android.CAM		

Severity	Code	Description	Project	File	Line	Suppression State	Suppression State
Error		"obj\Debug\81\MobileApp.Android.dll;obj\Debug\81\MobileApp.Android.dll" is an invalid value for the "OutputAssembly" parameter of the "Csc" task. Multiple items cannot be passed into a parameter of type "Microsoft.Build.Framework.ITaskItem".	MobileApp.Android

---
#### Visual Studio Feedback System on 12/1/2019, 11:09 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
