### ISSUE TITLE
High memory usage (DbCachedModel) with large number of tables (50k)

### ISSUE THREAD

**Issue by nvanlaerebeke** [dotnet/ef6#1557]
In our database there are a lot of tables, 50k and growing. For each table there is an object being kept in a static Dictionary in LazyInternalContext and am unable to minimize the number of entries (or turn it off)

I was expecting 'some' way to minimize this, this is used in a service so if one of those tables is queried once every week I expect to be able to remove it from that Dictionary somehow.

### Steps to reproduce
1. query x number of tables
2. use a memory profiler or debugger and see what's in  "InitializedDatabases"
This is the location where the dictionary is being filled:
https://github.com/dotnet/ef6/blob/master/src/EntityFramework/Internal/LazyInternalContext.cs#L670

Expected:
Some way to skip/manage that dictionary

Result:
InitializedDatabases.Count() is always the number of tables that were queried during the application lifetime

### Further technical details
EF version: 6.4.0
Database Provider: EntityFramework6.Npgsql
Operating system: Windows 10, Mono(6.6.0)
IDE: Visual Studio 2019 16.4.2

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
