### ISSUE TITLE
Migrations created .designer.cs in csproj lowercase but file is Uppercase

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/ef6#1575]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/895496/migrations-created-designercs-in-csproj-lowercase.html)._

---
When we create a new migration with EntityFramework6\add-migration command, the package manager creates the Migrations designer file in uppercase . Designer.cs but writes it to the project file aslowercase .designer.cs which leads to build issues like this

"/usr/app/xx.xx/xx.xx.csproj" (default target) (4:3) ->

(CoreCompile target) -> 

CSC : error CS2001: Source file '/usr/app/xx.xx/Migrations/202001231417379_Merge_202001231517.designer.cs' could not be found. [/usr/app/xx.xx/xx.xx.csproj]

---
### Original Comments
(no comments)

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
