### ISSUE TITLE
Tilde field names in Entity Framework

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/ef6#1596]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/917362/nombres-de-campo-con-tilde-en-entity-framework.html)._

---
If in two different tables I have a field with the same name, but one with tilde and one without it, such as Number and Number or Address and Address, for example, it causes problems loading the related entities.

An example:

Table1 has two fields related to other tables Table1.Table2Id and Table1.Table3Id, and in Table2 and Table3 there is the same field, one with tilde and one without it: Table2.Address and Table3.Address (in the SQL collation is case insensitive and accent insensitive).

If in Entity Framework we make such a call:

context. Table1.Include("Table2"). Include("Table3")

It gives us the following error: "Address column has been specified multiple times for Project1"

A greeting

---
#### Visual Studio Feedback System on 2/13/2020, 08:29 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CarlosAdrianM** [comment]
It is needed to check the original post in Spanish, because the point here is the difference between "Número" and "Numero", or "Dirección" and "Direccion". In the translated text "Number" and "Number" are exactly equal, so there is no problem.

**Comment by ajcvickers** [comment]
@CarlosAdrianM Do you have any ideas on what EF could do differently here?

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
