### ISSUE TITLE
Unit testing EF Context

### ISSUE THREAD

**Issue by KevinBurton** [dotnet/ef6#1606]
Describe what is not working as expected.

### Steps to reproduce
From [Async Query](https://docs.microsoft.com/en-us/ef/ef6/fundamentals/testing/mocking
). I get the following code.

            var mockSet = new Mock<DbSet<Blog>>();
            mockSet.As<IDbAsyncEnumerable<Blog>>()
                .Setup(m => m.GetAsyncEnumerator())
                .Returns(new TestDbAsyncEnumerator<Blog>(data.GetEnumerator()));

However I receive a warning when I compile like

>xxx: warning CA2000: Call System.IDisposable.Dispose on object created by 'new TestDbAsyncEnumerator<Blog>(data.GetEnumerator())' before all references to it are out of scope.

along with a squiggly green line in the code.

How do I get rid of the warning. I tried the suggested fix but it seems dependent on the name of the unused variable. If I have to test more than one DbSet it doesn't seem to work?

### Further technical details
EF version: 6.4
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2019 16.4.5

**Comment by ajcvickers** [comment]
@KevinBurton I would strongly advise against attempting to mock async LINQ. It's just a world of pain.

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
