### ISSUE TITLE
Query optimizations for bool on SQL Server

### ISSUE THREAD

**Issue by FlorianRainer** [dotnet/ef6#1649]
I've made the following tests on a Entity with a `bool` property named `Deleted`

Case 1:
```c#
 query.Where(x => x.Deleted)
```
```SQL
 ... WHERE Deleted = 1 ...
```
This case is correctly optimized.

Case 2:
```c#
 query.Where(x => !x.Deleted)
```
```SQL
 ... WHERE Deleted != 1 ...
```
This case is not well optimized for the way how SQL Server uses indices related to Equality and InEquality operators. in this case the queryplan could skip usefull indices.

Workaround:
```c#
 query.Where(x => x.Deleted == false)
```
```SQL
 ... WHERE Deleted = 0 ...
```

according to my tests SQL server is not able to implicit optimize the query (convert this inequality to equality for `bit` datatype) at least not on CompatibilityVersion 100

Is there any setting i've missed or nobody has noticed this so far

### Further technical details
EF version: 6.4
Database Provider: EntityFramework.SqlServer

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
