### ISSUE TITLE
Performance regression in query plan compilation under load on .Net Core

### ISSUE THREAD

**Issue by ArturDorochowicz** [dotnet/ef6#1794]
I believe there's a performance regression in query plan compilation under load with EF 6.4.4 on .Net Core 3.1.

### Background
We run a somewhat active web application. We have recently upgraded it from net48 and EF 6.2.0 to netcoreapp3.1 and EF 6.4.4. 

The application has been long in development so some patterns used there are not necessarily up to date. In particular there's a considerable amount of synchronous IO. This, I think, puts pressure on the thread pool which often runs with elevated number of worker threads (2x - 3x the default, i.e. equal to the number of CPUs). When it happens, we see sustained, increased processor usage making the application slow. 

Traces that we took point to EF query plan compilations (which happen in our case because some of the frequent queries in the app don't get cached) and specifically to the use of ConcurrentBag in BitVec.ArrayPool..

### Benchmarks
I've tried to show the issue with BenchmarkDotNet benchmarks. Below are the results of it. Note that I'm completely new to BenchmarkDotNet. Still, I think it shows there's an issue. 

Benchmarks are completely synthetic, all they do is compile a plan for a non trivial query in a loop on multiple threads in parallel. 
Base benchmark class is taken from grpc project (https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Microbenchmarks/CommonThreadedBase.cs)

**Edit:** I managed to run all the cases in one benchmark. Results in a comment further below: https://github.com/dotnet/ef6/issues/1794#issuecomment-759274014

Benchmarks were run on a 4 core cpu (8 logical cores). There are three comparisons (results and project sources further below):
1. EF 6.4.4 net48 V. EF 6.4.4 netcoreapp3.1 - with growing number number of threads, EF on netcoreapp3.1 is more and more underperforming
2. EF 6.2.0 net48 V. EF 6.4.4 netcoreapp3.1 - similar situation to the above, but EF on netcoreapp3.1 underperforms even more with growing number of threads
3. EF 6.2.0 net48 V. EF 6.4.4 net48 - there's not much of a difference, but seems that 6.2.0 might be just a bit more "scalable" than 6.4.4

### EF 6.4.4 net48 V. EF 6.4.4 netcoreapp3.1

``` ini

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19042
Intel Core i7-7700HQ CPU 2.80GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
  [Host]     : .NET Framework 4.8 (4.8.4300.0), X64 RyuJIT
  Job-QKEGVM : .NET Framework 4.8 (4.8.4300.0), X64 RyuJIT
  Job-YDYBRC : .NET Core 3.1.10 (CoreCLR 4.700.20.51601, CoreFX 4.700.20.51901), X64 RyuJIT

Server=True  RunStrategy=Monitoring  

```
|          Method |        Job |       Runtime | ThreadCount |      Mean |     Error |    StdDev | Ratio | RatioSD |
|---------------- |----------- |-------------- |------------ |----------:|----------:|----------:|------:|--------:|
| **PlanCompilation** | **Job-QKEGVM** |      **.NET 4.8** |           **4** |  **2.968 ms** | **0.0187 ms** | **0.0124 ms** |  **1.00** |    **0.00** |
| PlanCompilation | Job-YDYBRC | .NET Core 3.1 |           4 |  2.862 ms | 0.0323 ms | 0.0214 ms |  0.96 |    0.01 |
|                 |            |               |             |           |           |           |       |         |
| **PlanCompilation** | **Job-QKEGVM** |      **.NET 4.8** |           **8** |  **4.804 ms** | **0.0099 ms** | **0.0065 ms** |  **1.00** |    **0.00** |
| PlanCompilation | Job-YDYBRC | .NET Core 3.1 |           8 |  4.653 ms | 0.0621 ms | 0.0411 ms |  0.97 |    0.01 |
|                 |            |               |             |           |           |           |       |         |
| **PlanCompilation** | **Job-QKEGVM** |      **.NET 4.8** |          **16** |  **9.521 ms** | **0.0309 ms** | **0.0204 ms** |  **1.00** |    **0.00** |
| PlanCompilation | Job-YDYBRC | .NET Core 3.1 |          16 | 10.247 ms | 0.1164 ms | 0.0770 ms |  1.08 |    0.01 |
|                 |            |               |             |           |           |           |       |         |
| **PlanCompilation** | **Job-QKEGVM** |      **.NET 4.8** |          **32** | **20.607 ms** | **0.0509 ms** | **0.0337 ms** |  **1.00** |    **0.00** |
| PlanCompilation | Job-YDYBRC | .NET Core 3.1 |          32 | 23.783 ms | 0.1388 ms | 0.0918 ms |  1.15 |    0.01 |
|                 |            |               |             |           |           |           |       |         |
| **PlanCompilation** | **Job-QKEGVM** |      **.NET 4.8** |          **48** | **33.281 ms** | **0.3638 ms** | **0.2406 ms** |  **1.00** |    **0.00** |
| PlanCompilation | Job-YDYBRC | .NET Core 3.1 |          48 | 41.700 ms | 0.0804 ms | 0.0532 ms |  1.25 |    0.01 |
|                 |            |               |             |           |           |           |       |         |
| **PlanCompilation** | **Job-QKEGVM** |      **.NET 4.8** |          **64** | **46.142 ms** | **1.2801 ms** | **0.8467 ms** |  **1.00** |    **0.00** |
| PlanCompilation | Job-YDYBRC | .NET Core 3.1 |          64 | 63.083 ms | 0.1209 ms | 0.0799 ms |  1.37 |    0.02 |

[TestEFRecompilation_644_644.zip](https://github.com/dotnet/ef6/files/5798080/TestEFRecompilation_644_644.zip)

### EF 6.2.0 net48 V.  EF 6.4.4 netcoreapp3.1

``` ini

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19042
Intel Core i7-7700HQ CPU 2.80GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
  [Host]     : .NET Framework 4.8 (4.8.4300.0), X64 RyuJIT
  Job-QKEGVM : .NET Framework 4.8 (4.8.4300.0), X64 RyuJIT
  Job-YDYBRC : .NET Core 3.1.10 (CoreCLR 4.700.20.51601, CoreFX 4.700.20.51901), X64 RyuJIT

Server=True  RunStrategy=Monitoring  

```
|          Method |        Job |       Runtime | ThreadCount |      Mean |     Error |    StdDev | Ratio |
|---------------- |----------- |-------------- |------------ |----------:|----------:|----------:|------:|
| **PlanCompilation** | **Job-QKEGVM** |      **.NET 4.8** |           **4** |  **3.120 ms** | **0.0250 ms** | **0.0166 ms** |  **1.00** |
| PlanCompilation | Job-YDYBRC | .NET Core 3.1 |           4 |  2.752 ms | 0.0067 ms | 0.0044 ms |  0.88 |
|                 |            |               |             |           |           |           |       |
| **PlanCompilation** | **Job-QKEGVM** |      **.NET 4.8** |           **8** |  **4.989 ms** | **0.0574 ms** | **0.0380 ms** |  **1.00** |
| PlanCompilation | Job-YDYBRC | .NET Core 3.1 |           8 |  4.619 ms | 0.0372 ms | 0.0246 ms |  0.93 |
|                 |            |               |             |           |           |           |       |
| **PlanCompilation** | **Job-QKEGVM** |      **.NET 4.8** |          **16** |  **9.841 ms** | **0.0228 ms** | **0.0151 ms** |  **1.00** |
| PlanCompilation | Job-YDYBRC | .NET Core 3.1 |          16 | 10.127 ms | 0.1660 ms | 0.1098 ms |  1.03 |
|                 |            |               |             |           |           |           |       |
| **PlanCompilation** | **Job-QKEGVM** |      **.NET 4.8** |          **32** | **20.541 ms** | **0.0931 ms** | **0.0616 ms** |  **1.00** |
| PlanCompilation | Job-YDYBRC | .NET Core 3.1 |          32 | 24.051 ms | 0.1034 ms | 0.0684 ms |  1.17 |
|                 |            |               |             |           |           |           |       |
| **PlanCompilation** | **Job-QKEGVM** |      **.NET 4.8** |          **48** | **31.539 ms** | **0.2406 ms** | **0.1591 ms** |  **1.00** |
| PlanCompilation | Job-YDYBRC | .NET Core 3.1 |          48 | 41.739 ms | 0.1223 ms | 0.0809 ms |  1.32 |
|                 |            |               |             |           |           |           |       |
| **PlanCompilation** | **Job-QKEGVM** |      **.NET 4.8** |          **64** | **43.353 ms** | **0.5174 ms** | **0.3422 ms** |  **1.00** |
| PlanCompilation | Job-YDYBRC | .NET Core 3.1 |          64 | 62.850 ms | 0.3439 ms | 0.2275 ms |  1.45 |

[TestEFRecompilation_620_644.zip](https://github.com/dotnet/ef6/files/5798097/TestEFRecompilation_620_644.zip)

### EF 6.2.0 net48 V. EF 6.4.4 net48

``` ini

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19042
Intel Core i7-7700HQ CPU 2.80GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
  [Host]     : .NET Framework 4.8 (4.8.4300.0), X64 RyuJIT
  Job-DQVCDR : .NET Framework 4.8 (4.8.4300.0), X64 RyuJIT
  Job-CMOCQR : .NET Framework 4.8 (4.8.4300.0), X64 RyuJIT

Server=True  Arguments=/p:AutoGenerateBindingRedirects=false,/p:GenerateSupportedRuntime=false  RunStrategy=Monitoring  

```
|          Method |        Job |       NuGetReferences | ThreadCount |      Mean |     Error |    StdDev | Ratio |
|---------------- |----------- |---------------------- |------------ |----------:|----------:|----------:|------:|
| **PlanCompilation** | **Job-DQVCDR** | **EntityFramework 6.2.0** |           **4** |  **3.119 ms** | **0.0258 ms** | **0.0171 ms** |  **1.00** |
| PlanCompilation | Job-CMOCQR | EntityFramework 6.4.4 |           4 |  2.979 ms | 0.0424 ms | 0.0280 ms |  0.96 |
|                 |            |                       |             |           |           |           |       |
| **PlanCompilation** | **Job-DQVCDR** | **EntityFramework 6.2.0** |           **8** |  **4.955 ms** | **0.0215 ms** | **0.0142 ms** |  **1.00** |
| PlanCompilation | Job-CMOCQR | EntityFramework 6.4.4 |           8 |  4.774 ms | 0.0996 ms | 0.0659 ms |  0.96 |
|                 |            |                       |             |           |           |           |       |
| **PlanCompilation** | **Job-DQVCDR** | **EntityFramework 6.2.0** |          **16** |  **9.885 ms** | **0.0468 ms** | **0.0310 ms** |  **1.00** |
| PlanCompilation | Job-CMOCQR | EntityFramework 6.4.4 |          16 |  9.658 ms | 0.1366 ms | 0.0904 ms |  0.98 |
|                 |            |                       |             |           |           |           |       |
| **PlanCompilation** | **Job-DQVCDR** | **EntityFramework 6.2.0** |          **24** | **15.039 ms** | **0.0459 ms** | **0.0304 ms** |  **1.00** |
| PlanCompilation | Job-CMOCQR | EntityFramework 6.4.4 |          24 | 15.082 ms | 0.0397 ms | 0.0262 ms |  1.00 |
|                 |            |                       |             |           |           |           |       |
| **PlanCompilation** | **Job-DQVCDR** | **EntityFramework 6.2.0** |          **32** | **20.460 ms** | **0.0529 ms** | **0.0350 ms** |  **1.00** |
| PlanCompilation | Job-CMOCQR | EntityFramework 6.4.4 |          32 | 20.743 ms | 0.2705 ms | 0.1789 ms |  1.01 |
|                 |            |                       |             |           |           |           |       |
| **PlanCompilation** | **Job-DQVCDR** | **EntityFramework 6.2.0** |          **40** | **25.990 ms** | **0.1027 ms** | **0.0679 ms** |  **1.00** |
| PlanCompilation | Job-CMOCQR | EntityFramework 6.4.4 |          40 | 27.078 ms | 0.2125 ms | 0.1406 ms |  1.04 |
|                 |            |                       |             |           |           |           |       |
| **PlanCompilation** | **Job-DQVCDR** | **EntityFramework 6.2.0** |          **48** | **32.105 ms** | **0.3490 ms** | **0.2308 ms** |  **1.00** |
| PlanCompilation | Job-CMOCQR | EntityFramework 6.4.4 |          48 | 33.421 ms | 0.5360 ms | 0.3545 ms |  1.04 |

[TestEFRecompilation_620_644_net48.zip](https://github.com/dotnet/ef6/files/5798105/TestEFRecompilation_620_644_net48.zip)

### Benchmark code

Benchmark code is basically the following, see zip archives for actual projects.
```csharp
  public void PlanCompilation()
  {
      RunConcurrent(() => { RunBody(); });
  }

  public static void RunBody()
  {
      using (var ctx = new TestContext("Server=(localdb)\\MSSQLLocalDB; Database=EFBenchmark1;"))
      {
          for (var i = 0; i < 10000; i++)
          {
              var query = GetQuery(ctx);
              var sql = query.ToString();
              _ = sql;
          }
      }
  }

  static IQueryable GetQuery(TestContext context)
  {
      var ids = new[] {1, 2};

      return from employee in context.Employees
          where ids.Contains(employee.Id)
          join other in context.Employees on employee.ManagerId equals other.Id into managers
          from manager in managers.DefaultIfEmpty()
          join other in context.Employees on employee.Id equals other.ManagerId into reports
          select new
          {
              Id = employee.Id,
              Name = employee.Name,
              ManagerId = manager != null ? manager.Id : (int?)null,
              ManagerName = manager != null ? manager.Name : null,
              ReportsCount = reports.Count()
          };
  }

  public class TestContext : DbContext
  {
      public TestContext(string connectionString)
          : base(connectionString)
      {
          Database.SetInitializer<TestContext>(null);
      }

      public DbSet<Employee> Employees { get; set; }
  }

  public class Employee
  {
      public int Id { get; set; }

      public int? ManagerId { get; set; }

      public string Name { get; set; }
  }
```

**Comment by Seabizkit** [comment]
Random question, but how do you do 64 threads on say....
"Intel Core i7-7700HQ CPU 2.80GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores"
Work? surely the tests beyond the actually limits... are meaningless or will show regression on both.

**Comment by ArturDorochowicz** [comment]
As I learn more about BenchmarkDotNet, I was able to run all the cases in one benchmark for easier comparison.

[TestEFRecompilation.zip](https://github.com/dotnet/ef6/files/5807182/TestEFRecompilation.zip)

Run with `dotnet run -c Release -f net48 -- -f *`
``` ini

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19042
Intel Core i7-7700HQ CPU 2.80GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
  [Host]     : .NET Framework 4.8 (4.8.4300.0), X64 RyuJIT
  Job-EJNHXU : .NET Framework 4.8 (4.8.4300.0), X64 RyuJIT
  Job-IRUXDQ : .NET Framework 4.8 (4.8.4300.0), X64 RyuJIT
  Job-SHNZVZ : .NET Core 3.1.10 (CoreCLR 4.700.20.51601, CoreFX 4.700.20.51901), X64 RyuJIT

Server=True  Arguments=/p:AutoGenerateBindingRedirects=false,/p:GenerateSupportedRuntime=false  RunStrategy=Monitoring  

```
|          Method |        Job |       Runtime |       NuGetReferences | ThreadCount |      Mean |     Error |    StdDev | Ratio |
|---------------- |----------- |-------------- |---------------------- |------------ |----------:|----------:|----------:|------:|
| **PlanCompilation** | **Job-EJNHXU** |      **.NET 4.8** | **EntityFramework 6.2.0** |           **4** |  **3.119 ms** | **0.0241 ms** | **0.0159 ms** |  **1.00** |
| PlanCompilation | Job-IRUXDQ |      .NET 4.8 | EntityFramework 6.4.4 |           4 |  2.988 ms | 0.0328 ms | 0.0217 ms |  0.96 |
| PlanCompilation | Job-SHNZVZ | .NET Core 3.1 | EntityFramework 6.4.4 |           4 |  2.760 ms | 0.0223 ms | 0.0147 ms |  0.88 |
|                 |            |               |                       |             |           |           |           |       |
| **PlanCompilation** | **Job-EJNHXU** |      **.NET 4.8** | **EntityFramework 6.2.0** |           **8** |  **4.952 ms** | **0.0451 ms** | **0.0298 ms** |  **1.00** |
| PlanCompilation | Job-IRUXDQ |      .NET 4.8 | EntityFramework 6.4.4 |           8 |  4.720 ms | 0.0190 ms | 0.0126 ms |  0.95 |
| PlanCompilation | Job-SHNZVZ | .NET Core 3.1 | EntityFramework 6.4.4 |           8 |  4.589 ms | 0.0311 ms | 0.0205 ms |  0.93 |
|                 |            |               |                       |             |           |           |           |       |
| **PlanCompilation** | **Job-EJNHXU** |      **.NET 4.8** | **EntityFramework 6.2.0** |          **16** |  **9.771 ms** | **0.0496 ms** | **0.0328 ms** |  **1.00** |
| PlanCompilation | Job-IRUXDQ |      .NET 4.8 | EntityFramework 6.4.4 |          16 |  9.524 ms | 0.0369 ms | 0.0244 ms |  0.97 |
| PlanCompilation | Job-SHNZVZ | .NET Core 3.1 | EntityFramework 6.4.4 |          16 | 10.140 ms | 0.0340 ms | 0.0225 ms |  1.04 |
|                 |            |               |                       |             |           |           |           |       |
| **PlanCompilation** | **Job-EJNHXU** |      **.NET 4.8** | **EntityFramework 6.2.0** |          **24** | **15.078 ms** | **0.0826 ms** | **0.0546 ms** |  **1.00** |
| PlanCompilation | Job-IRUXDQ |      .NET 4.8 | EntityFramework 6.4.4 |          24 | 15.077 ms | 0.0507 ms | 0.0335 ms |  1.00 |
| PlanCompilation | Job-SHNZVZ | .NET Core 3.1 | EntityFramework 6.4.4 |          24 | 16.854 ms | 0.0886 ms | 0.0586 ms |  1.12 |
|                 |            |               |                       |             |           |           |           |       |
| **PlanCompilation** | **Job-EJNHXU** |      **.NET 4.8** | **EntityFramework 6.2.0** |          **32** | **20.554 ms** | **0.0824 ms** | **0.0545 ms** |  **1.00** |
| PlanCompilation | Job-IRUXDQ |      .NET 4.8 | EntityFramework 6.4.4 |          32 | 20.790 ms | 0.1090 ms | 0.0721 ms |  1.01 |
| PlanCompilation | Job-SHNZVZ | .NET Core 3.1 | EntityFramework 6.4.4 |          32 | 24.032 ms | 0.0418 ms | 0.0276 ms |  1.17 |
|                 |            |               |                       |             |           |           |           |       |
| **PlanCompilation** | **Job-EJNHXU** |      **.NET 4.8** | **EntityFramework 6.2.0** |          **40** | **26.222 ms** | **0.1503 ms** | **0.0994 ms** |  **1.00** |
| PlanCompilation | Job-IRUXDQ |      .NET 4.8 | EntityFramework 6.4.4 |          40 | 27.471 ms | 0.1849 ms | 0.1223 ms |  1.05 |
| PlanCompilation | Job-SHNZVZ | .NET Core 3.1 | EntityFramework 6.4.4 |          40 | 31.987 ms | 0.0581 ms | 0.0384 ms |  1.22 |
|                 |            |               |                       |             |           |           |           |       |
| **PlanCompilation** | **Job-EJNHXU** |      **.NET 4.8** | **EntityFramework 6.2.0** |          **48** | **31.868 ms** | **0.3347 ms** | **0.2214 ms** |  **1.00** |
| PlanCompilation | Job-IRUXDQ |      .NET 4.8 | EntityFramework 6.4.4 |          48 | 33.757 ms | 0.5301 ms | 0.3507 ms |  1.06 |
| PlanCompilation | Job-SHNZVZ | .NET Core 3.1 | EntityFramework 6.4.4 |          48 | 41.626 ms | 0.1623 ms | 0.1073 ms |  1.31 |

**Comment by ArturDorochowicz** [comment]
> Random question, but how do you do 64 threads on say....
> "Intel Core i7-7700HQ CPU 2.80GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores"
> Work? surely the tests beyond the actually limits... are meaningless or will show regression on both.

@Seabizkit Sure, I may have gone overboard with this. OTOH, it doesn't show regression on both, but rather it confirms the trend of EF on .net core underperforming under load more and more.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.

**Comment by Poltuu** [comment]
We just spend 8 month trying to understand why our application freshly migrated from .NET4.8 could not handle the load, never thinking that the time spent compiling plans was abnormal of all things. We now have to migrate to EF Core, which is no little task.

This issue should be clearly advertised in this repo's front page, and serve as a warning for anyone trying to migrate big apps to dotnet core, while still using EF 6.

**Comment by FPierrel** [comment]
We've seen the same problem this week. In some cases, the loss of time due to the use of ConcurrentBag is greater than 30%.

Have you tested a return to EF6.3? We haven't had time to do so yet. We are also considering the creation of a custom version without the PR that introduces this counter-productive 'optimization' (https://github.com/dotnet/ef6/pull/430).

**Comment by briandesarmo** [comment]
### Adding measurements: the cost grows with process *uptime*, and .NET 10 doesn't fix it

We hit this on a large .NET 8 server app using EF6 6.5, migrated from .NET Framework 4.8. Same signature as the original report: sustained 100% CPU, threads in cooperative mode, no lock contention, hot leaf at `ConcurrentBag<int[]>.TrySteal` under `BitVec.ArrayPool.GetArray` inside `PlanCompiler.Compile`.

Since this thread is where people land when they search for it, here is what we measured, plus a workaround that doesn't require forking EF6.

#### The part that wasn't identified here: dead-thread queues are never reclaimed

`ConcurrentBag<T>` allocates a work-stealing queue per thread on first touch. The pool is a **process-lifetime static**, and on .NET Core and later, queues belonging to threads that have since exited are not reused in practice. So the steal walk doesn't scale with *concurrency* — it scales with **the cumulative number of threads that have ever compiled a query**, and it only ever grows.

That's why the symptom is "gets slower the longer the process runs, and a restart temporarily fixes it", which is easy to misattribute to a leak.

#### Measurements

A standalone probe modelling EF6's usage: a static `ConcurrentBag<int[]>`; N threads each touch the bag once and **terminate** (all `Join`ed); then measure `TryTake` against an empty bag (EF6's miss path) versus `new int[4]`. Identical source compiled for three runtimes, 20 cores.

| queues touched (all threads dead) | **.NET Framework 4.8** | **.NET 8** | **.NET 10** |
|---:|---:|---:|---:|
| 0 | 56.6 ns | 24.5 ns | 31.9 ns |
| 25 | 48.1 ns | 524 ns | 604 ns |
| 75 | 48.8 ns | 1,599 ns | 1,463 ns |
| 175 | 49.0 ns | 3,776 ns | 3,281 ns |
| 375 | 51.5 ns | 8,300 ns | 6,795 ns |
| 875 | **49.2 ns** | **19,254 ns** | **12,220 ns** |

`new int[4]` measured at **0.4–3.6 ns** on all three.

- **.NET Framework is flat** regardless of dead-thread count — consistent with its `ConcurrentBag` reusing the thread-local list of a stopped thread.
- **.NET 8 is linear at ~22 ns per queue.** At 875 queues it is **391× slower** than .NET Framework, and the pool costs roughly **35,000× more than the allocation it exists to avoid**.
- **.NET 10 does not fix it.** The constant improves to ~14 ns/queue (~1.6×), but it is still O(queues) with no reclamation — still **248× slower** than .NET Framework at 875 queues. Worth knowing if you were hoping a runtime upgrade would resolve this.

A production dump of ours showed 489 threads, 389 of them dead — about **10.8 µs per `GetArray` miss** on .NET 8.

#### Why it's worse than the numbers suggest

The usage is **net-draining**: `GetArray` runs in every `BitVec` constructor, but `PutArray` only runs on grow/shrink in the `Length` setter. So the bag is usually empty, meaning nearly every call pays the **full walk and then allocates anyway**.

#### Workaround without forking EF6

The pool holds nothing but spare arrays, so its state can simply be thrown away. Replacing the bags resets the queue count to zero:

```csharp
var bitVec = typeof(DbContext).Assembly
    .GetType("System.Data.Entity.Core.Query.InternalTrees.BitVec");
var poolType = bitVec.GetNestedType("ArrayPool", BindingFlags.NonPublic);
var instance = poolType.GetField("instance", BindingFlags.NonPublic | BindingFlags.Static)
                       .GetValue(null);
var pool = (ConcurrentDictionary<int, ConcurrentBag<int[]>>)poolType
    .GetField("dictionary", BindingFlags.NonPublic | BindingFlags.Instance)
    .GetValue(instance);

// on a timer, e.g. every 60s
foreach (var length in pool.Keys)
    pool[length] = new ConcurrentBag<int[]>();
```

Measured against EF 6.5:

```
baseline (fresh bag)      |     26.6 ns
after 500 dead threads    |  11,093.2 ns
after 1000 dead threads   |  23,397.5 ns
AFTER RESET               |     12.7 ns   ← 1,842× recovery
```

This is safe because arrays in use are owned by live `BitVec` instances via `m_array` and are untouched; arrays in the discarded bag just become garbage; a thread still holding the old bag either takes from it or allocates; and the `ConcurrentDictionary` indexer assignment is atomic. It's reflection into private internals, so resolve the shape once at startup and disable the feature if anything has moved — if it fails you're simply back to current behaviour.

#### If EF6 ever takes a fix here

Given `new int[4]` costs ~0.5 ns, `ArrayPool<int>.Shared` or plain allocation would both be strictly better than the current pool on .NET Core and later. The pool arrived in #430, which targeted *very large single queries* on a single thread — a reasonable goal at the time, and one whose trade-off inverted with the `ConcurrentBag` rewrite.

#### Repro

```csharp
using System.Collections.Concurrent;
using System.Diagnostics;

var bag = new ConcurrentBag<int[]>();
const int Iterations = 200_000;
int total = 0;

Report(0);
foreach (var batch in new[] { 25, 50, 100, 200, 500 })
{
    var threads = new Thread[batch];
    for (int i = 0; i < batch; i++)
    {
        threads[i] = new Thread(() => { bag.Add(new int[4]); bag.TryTake(out _); });
        threads[i].Start();
    }
    foreach (var t in threads) t.Join();   // every thread is dead before we measure
    total += batch;
    Report(total);
}

void Report(int queues)
{
    while (bag.TryTake(out _)) { }
    var sw = Stopwatch.StartNew();
    for (int i = 0; i < Iterations; i++) bag.TryTake(out _);
    sw.Stop();
    Console.WriteLine($"{queues,6} queues | {sw.Elapsed.TotalMilliseconds * 1e6 / Iterations,10:F1} ns/op");
}
```

**Comment by briandesarmo** [comment]
#### Correction to my earlier comment: the queue count is bounded by *peak concurrency*, not cumulative threads

In [my comment above](https://github.com/dotnet/ef6/issues/1794#issuecomment-5248753525) I said the steal walk "scales with the cumulative number of threads that have ever compiled a query, and it only ever grows." That overstates it, and I'd rather correct it than leave a wrong claim in a thread people land on when searching for this.

I've since reproduced the problem end-to-end in the real application rather than only in a standalone probe, and the queue count behaves differently there.

**What I got wrong.** My probe created N threads, joined them all, and then measured — and saw exactly N retained queues, which looked like unbounded growth. But that probe created threads faster than the runtime recycled managed thread IDs, so `GetUnownedWorkStealingQueue`'s check on `_ownerThreadId == Environment.CurrentManagedThreadId` essentially never matched. In a real process it matches fairly often.

**What actually happens.** Measured through the application's search path against a real database:

| concurrent threads | total threads created | retained queues |
|---:|---:|---:|
| 50 | 500 | 251 |
| 50 | 4,000 | 503 |
| 90 | 20,000 | 906 |

A 5× increase in *total* threads (4,000 → 20,000) barely moved the count. A 1.8× increase in *concurrency* moved it 1.8×. The retained queue count tracks roughly **10× the peak concurrent thread count** and saturates there.

**Why the conclusion doesn't change.** The count never *falls*. It settles at a level set by the busiest the process has ever been, and a high-water mark only ratchets upward, so the cost still rises over process lifetime and still only recovers on restart. The observable symptom — degradation correlated with uptime, temporarily fixed by a restart — is unchanged, and so is the fix.

It also means the ceiling is set by peak thread count rather than request count, which matters for anyone using a provider that starts a thread per command. Ours does, which is how a few hundred concurrent users produced ~900 queues.

#### End-to-end numbers, since the earlier ones were synthetic

Same query, same data, warmed server, only the pool state differing:

| pool state | median query time |
|---|---:|
| 1 queue (just reset) | 33.2 ms |
| 905 queues | 69.5 ms |

**2.1× on a real workload.** Worth noting the ordering: the 905-queue measurement ran *after* the 1-queue measurement, so ordinary warm-up was biasing it faster. 2.1× is a floor, not a ceiling.

This is also why this is so hard to reproduce locally, which I suspect is part of why the issue sat open. It's driven by sustained concurrency, not by volume — a developer hammering the app on a handful of long-lived threads will never accumulate queues no matter how many queries they run.

The `Timer`-based workaround in my earlier comment is unaffected by any of this and still measures the same.

**Comment by CZEMacLeod** [comment]
@briandesarmo Thanks for this!
We have some major EF6 based apps which have been migrated (or are being migrated) and this seems like it could be a lifesaver for some of them.
We currently have nightly restarts of the applications (carried over from IIS app pool resets) and this seems to have mitigated the issue partially, but your solution looks like it could really help.

I have wrapped it up as a `BackgroundService` which can be easily registered in services.
Hope this helps.

````cs
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using System.Collections.Concurrent;
using System.Data.Entity;
using System.Reflection;

public static class BagManExtensions
{
    public static IServiceCollection AddEF6BagMan(this IServiceCollection services, Action<BagManOptions>? configure = null, string sectionName = "EF6:BagMan")
    {
        services.AddOptions<BagManOptions>().BindConfiguration(sectionName).Configure(configure ?? (_ => { }));
        services.AddHostedService<BagMan>();
        return services;
    }
}

public class BagManOptions
{
    public bool Enabled { get; set; } = true;
    public TimeSpan Period { get; set; } = TimeSpan.FromSeconds(60);
}

public class BagMan : BackgroundService
{
    private readonly ConcurrentDictionary<int, ConcurrentBag<int[]>>? pool;
    private readonly ILogger<BagMan> logger;
    private readonly IOptions<BagManOptions> options;

    public BagMan(ILogger<BagMan> logger, IOptions<BagManOptions> options)
    {
        this.logger = logger;
        this.options = options;

        if (options.Value.Enabled)
        {
            try
            {
                var bitVec = typeof(DbContext).Assembly
                    .GetType("System.Data.Entity.Core.Query.InternalTrees.BitVec");
                var poolType = bitVec.GetNestedType("ArrayPool", BindingFlags.NonPublic);
                var instance = poolType.GetField("instance", BindingFlags.NonPublic | BindingFlags.Static)
                                       .GetValue(null);
                pool = (ConcurrentDictionary<int, ConcurrentBag<int[]>>)poolType
                    .GetField("dictionary", BindingFlags.NonPublic | BindingFlags.Instance)
                    .GetValue(instance);
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "EF6 Internals Changed - please update code");
            }
        }
    }

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        if (pool is null || !options.Value.Enabled) return;

        while (!stoppingToken.IsCancellationRequested)
        {
            await Task.Delay(options.Value.Period, stoppingToken);
            try { 
                foreach (var length in pool.Keys)
                    pool[length] = new ConcurrentBag<int[]>();
            }
            catch (Exception ex) {
                logger.LogError(ex, "Error clearing pool");
            }
        }
    }
}
```
