### ISSUE TITLE
EF6 - SqlServer - IsUnicode setting not being honored when executing the linq

### ISSUE THREAD

**Issue by shvmgpt116** [dotnet/ef6#1949]
I have following sample application where I am setting IsUnicode(false) for "Content" Property.
```C#
using System;
using System.Data.Entity;
using System.Linq;

namespace EF6SqlServerTest
{
  class Program
  {
    static void Main(string[] args)
    {
      var connectionString = "<connection_string>";
      var ef6Context = new Context(connectionString);
      var ef6SQL = ef6Context.Messages.Select(t => t.Content + ".").ToString();
    }
  }

  public class Context : DbContext
  {
    public Context(string connectionString) : base(connectionString)
    {
    }

    public DbSet<Message> Messages { get; set; }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
      base.OnModelCreating(modelBuilder);
      modelBuilder.Entity<Message>().ToTable("MessageEF6").Property(t => t.Content).IsUnicode(false).IsVariableLength().IsOptional().HasMaxLength(1000);
    }
  }
  public class Message
  {
    public int Id { get; set; }
    public string Content { get; set; }
  }
}

```
Here is the table definition generated for Message entity when running the application-
```
CREATE TABLE [dbo].[MessageEF6] (
    [Id]      INT            IDENTITY (1, 1) NOT NULL,
    [Content] VARCHAR (1000) NULL,
    CONSTRAINT [PK_dbo.MessageEF6] PRIMARY KEY CLUSTERED ([Id] ASC)
);
```
But when I run the linq, here is the query that gets generated-
```
SELECT 
    CASE WHEN ([Extent1].[Content] IS NULL) THEN N'' ELSE [Extent1].[Content] END + N'.' AS [C1]
    FROM [dbo].[MessageEF6] AS [Extent1]
```
My question is why does the generated sql has N'' in the generated sql. It seems the generated query does not properly infer the mapping used for the Content column. Since Content is a normal VARCHAR type column, why is there any need to have unicode literal in the query?
Please could someone clarify.

### Further technical details
EF version: 6.4.4
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2019 16.11.2

**Comment by ErikEJ** [comment]
Because you are concatenating strings?

**Comment by shvmgpt116** [comment]
@ErikEJ I am not able to understand why using concatenating strings is causing to generate query with UNICODE string literals. Will there be any issue if the generated query doesn't have N' literal?

**Comment by CZEMacLeod** [comment]
@shvmgpt116 I think the point is two-fold. Firstly, EF6 is turning your .Net expression `t.Content + "."` into T-SQL. In .Net all strings are unicode so `+ "."` becomes `+ N'.'`.
Secondly, EF is bringing it back into a projected type in .Net which will, in this case, be a simple (unicode) string.
The unicodeness or otherwise of the field Content is actually irrelevant to the T-SQL generated as the result will be materialised in an `IEnumerable<string>` which will be unicode .
I guess, in this case, since the string you are concatenating could be represented without unicode, EF _could_ perform some magic to detect this and _not_ use the N'' mapping, but I doubt it would be much faster as the translation would still have to be done at some point to a .NET unicode string, and the SQL-ification code would be much more complicated (and probably slower).

If you want to force the content to be read from the database without unicode and do the string concatenation on the 'client' side, simply break your query.

```c#
	var query1 = ef6Context.Messages.Select(t => t.Content + ".");
	var ef6SQL1 = query1.ToString();
	Console.WriteLine(ef6SQL1);

	var query2 = ef6Context.Messages.Select(t => t.Content);
	var ef6SQL2 = query2.ToString();
	Console.WriteLine(ef6SQL2);
	var query3 = query2.AsEnumerable().Select(c => (c ?? "") + ".");
	var ef6SQL3 = query3.ToString();
	Console.WriteLine(ef6SQL3);
```

Obviously ef6SQL3 does not return SQL as it is using .Net based LINQ instead, however the result of query1 and query3 will be the same.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
