### ISSUE TITLE
What's the correct way to handle sql defaults?

### ISSUE THREAD

**Issue by micktion** [dotnet/ef6#2043]
Consider the following database schema...

```
	CREATE TABLE [dbo].[MyTable] (
		[ID]         INT
		[HDR_STATUS] INT CONSTRAINT [DF_HDRSTATUS] DEFAULT ('-1') NOT NULL
	)

```	

 With an entity as follows
 
```
	[Table("MyTable")]
	public partial class MyClass
	{
		public int ID { get; set; }
		
		public int HDR_STATUS {  get; set; }
	}
```
and in the context you have...

```
            modelBuilder
                .Entity<TestParent>()
                .Property(p => p.HDR_STATUS)
                .HasDefaultValueSql("'-1'");

```
If you add a record with HDR_Status set to 0, you actually end up with a record in the database with HDR_Status set to -1.

Now if you wanted to actually insert a record with HDR_Status = 0, how would you do it?  Remove the default value?

Is there some way of telling EF to omit the  HDR_STATUS from the insert when it is set to -1 instead?
```
            modelBuilder
                .Entity<TestParent>()
                .Property(p => p.HDR_STATUS)
                .HasDefaultValueSql("'-1'")
                .DefaultOn(-1);

```
Also correct me if I'm wrong but the value passed into HasDefaultValueSql(string sql) or HasDefaultValue(object value) seems to be completely superfluous, it might as well be just HasDefaultValue(), because of regardless of what is passed, the sql default is only used when the value of the field is the .NET default.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.

**Comment by micktion** [comment]
This was a question.  I still don't know what the correct way of dealing with this is.  

My solution is going to be simply don't use HasDefaultValueSql, or only use  HasDefaultValueSql when the default in the database is the same as the .NET default for the data type. 

Instead I'm using a code generator to grab the default from the database schema and generate a POCO class which sets those defaults in the constructor of the class. 

The main (minor) drawback of this approach is that Insert queries will include columns that could have been omitted, as some of the values being passed will be the same as the column's default value.  

For the particular case which prompted me to ask this question I don't have control over the DB schema I'm working with.  If I did I wouldn't create schema with defaults which are not the .NET default for the datatype, to simplify working with EF.

**Comment by CZEMacLeod** [comment]
@micktion As someone who has dealt with this scenario a little bit, my findings were that the use of defaultvaluesql was restricted to when you needed to set the schema up using a function - e.g. `NewID()` or `NewSequentialID()`. You might also use it to get the next value for a sequence such as `NEXT VALUE FOR dbo.EmployeePrimaryKey`
This is _primarily_ used during migrations where it creates the database for you. Also, in these cases, you might want to flag the field as database generated, so that it gets read back into the model for you as you won't know the e.g. sequence value until you save the record.
For your example I think what you want to do is use HasDefaultValue() and pass the .net value type that matches the database. You should also set the value in the initializer to match the default value in the database.
This way EF will know not to write the value if it matches the default value, and it will correctly write 0 if that is what is set.

FTR, your T-SQL seems to have a couple of oddities, but I assume they are just typos - missing command between fields, and why would you use the string '-1' instead of the value -1? This would seem to cause a cast on each record insertion.

Much of this is still the same in EFCore 6 which is the currently active/supported version, and provides some advantages over EF6 which, as @ajcvickers says, is no longer developed. 
Unfortunately, other than community support, this pretty much also means no longer supported in any way, beyond security fixes. For this kind of 'how to use' query, you would generally have been redirected to look at something like stackoverflow anyway.

Anyway, I hope this helps.
