### ISSUE TITLE
Migration renames many-to-many relation table

### ISSUE THREAD

**Issue by RCP161** [dotnet/ef6#407]
I'm using EF 6.2.0 in VS 2017 with CodeFirst.

I have a many to many relation between the Objects "Person" and "Testbench". The relation table is called "dbo.TestbenchPersons".

Now I added a class "Lincense" without any relation. The generated migration file added the class and all is fine.

If I add the class with a required reference to "Testbench", the migration file renames the many to many relation between "Person" and "Testbench" to "PersonTestbenches". This is a critical point. Other tools need the name and the relation or classnames didn't change.

Others have the same problem:
https://stackoverflow.com/questions/40907503/entity-framework-automatically-renaming-many-to-many-tables-without-any-changes

**Comment by brandondahler** [comment]
This issue has existed for a while (atleast pre-6.2, likely pre-6.1). 

The easiest way to work around the issue is to explicitly configure the many to many relationship on one of the entity types.  By doing this you will be specifying which entity is the primary and which is the dependent table and therefore which table should be named first.

``` C#
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<Testbench>()
                .HasMany(tb => tb.People)
                .WithMany(p => p.Testbenches);
        }
```

**Comment by RCP161** [comment]
Thanks for the answer. So no one will fix it? But is there an other way to handle this?
- Data Annotations
- Convention
- Disable Renaming
- Self mapped Relation Table (worst case)

Thanks

**Comment by ajcvickers** [comment]
@RCP161 This should only be an issue when a migration was created with an earlier version of EF and then a new migration is created with EF6.x. This was because the name was non-deterministic in earlier versions, but this as since been fixed. So it should be a one-time issue when updating to 6.x. The way to handle it is to either:
* Perform the one-off rename
* Configure the name explicitly so that it is no longer created by convention--see docs here: https://msdn.microsoft.com/en-us/library/jj591620(v=vs.113).aspx

**Comment by RCP161** [comment]
@ajcvickers This is a complete new Project with EF 6.2 . The rename is called, after some changes at the models, so a manual rename isn't verry helpful. Is there no way to handle this without fluent API. Why this will not be fixed? An explicit warning is shown because of the renaming.
This make sense, if i rename the classes, but not if i changed the properties.

**Comment by ajcvickers** [comment]
@RCP161 If it's happening just with EF6, then it may be a bug. Can you create a runnable project/solution that reproduces the issue so we can investigate?

**Comment by RCP161** [comment]
@ajcvickers In the EfIssue.Ef is an Info.txt. I hope this helps. I know, this isn't the regular way to use EF, but it would be nice, if you would check it.
[EfIssue.zip](https://github.com/aspnet/EntityFramework6/files/1538725/EfIssue.zip)

**Comment by ajcvickers** [comment]
@RCP161 Thanks for the repro code. I was able to see that the name changes even when the order in which entity types are registered does not change. Assigning to @AndriySvyryd to investigate,

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
