### ISSUE TITLE
Add-Migration fails to detect already applied migrations

### ISSUE THREAD

**Issue by xps** [dotnet/ef6#642]
I regularly get into the situation where I try to add a new migration, and get a message stating that the migration could not be created because previous migrations have not been applied to the database (they have). The problem resolves itself by simply closing and reopening Visual Studio, and running the `Add-Migration` command again.

````
PM> Add-Migration MyMigration -Verbose
````

> System.Data.Entity.Migrations.Infrastructure.MigrationsPendingException: Unable to generate an explicit migration because the following explicit migrations are pending: [... **list of all migrations in the project** ...]. Apply the pending explicit migrations before attempting to generate a new explicit migration.

Call stack:
````
   at System.Data.Entity.Migrations.DbMigrator.Scaffold(String migrationName, String namespace, Boolean ignoreChanges)
   at System.Data.Entity.Migrations.Design.MigrationScaffolder.Scaffold(String migrationName, Boolean ignoreChanges)
   at System.Data.Entity.Migrations.Design.ToolingFacade.ScaffoldRunner.Scaffold(MigrationScaffolder scaffolder)
   at System.Data.Entity.Migrations.Design.ToolingFacade.ScaffoldRunner.RunCore()
   at System.Data.Entity.Migrations.Design.ToolingFacade.BaseRunner.Run()
````

The previous message lists all migrations in the project as needing to be applied, as if it were a new database (it is not).

At that point if I try to run `Update-Database`, I get an error because the `__MigrationHistory` table already exists.

Using Entity Frameowork 6.2.0 on .NET 4.5.

I would try to troubleshoot this but I'm not sure how to attach a debugger to the `DbMigrator` class so that I can step through it?

**Comment by hbopuri** [comment]
I have similar problem. Were you able to every get this addressed? 
In my case, I upgrade from EF 6.13 to 6.2.0 then it says there are pending changes, when I run update-database, it is trying apply changes from my first migration and obviously it finds tables already there in DB and throws error.

**Comment by xps** [comment]
@hbopuri Is your problem fixed by restarting Visual Studio?

This problem can also simply be caused by VS not being able to reach your database server (incorrect connection string, network issues, etc.), so you have to rule this out.

Unfortunately no, I don't have a solution yet (other that restarting VS). I would like to debug (step through) the App-Migration command but I don't know how to go about that. I probably need to open that solution and attach the debugger to the other process or something like that.

I can also add that I recently reformatted my computer and the problem was there again right after the reset, so it's not a problem with anything corrupted in my OS.

Currently I am working on 3 projects, one on EF Core 2.1, one on EF 6 and the last one is a fork of the second one. I am having the issue on the 2 projects on EF 6 (so it could be something in the project, since they are both forked from the same code base).

**Comment by xps** [comment]
I also wanted to add, since this still happens to me on a daily basis, that I tried to unload and reload the current solution but that is not enough to fix the problem. Visual Studio has to be restarted.

If someone could give me instructions on how to troubleshoot (ideally step through the code of the Add-Migration command), I would be happy to dig into this.

**Comment by creativesuspects** [comment]
I'm having the same issue after upgrading from EF 6.4.0 to EF 6.4.4. I can't add a new migration because EF says that none of the previous migrations have been applied:

![image](https://user-images.githubusercontent.com/161342/144874587-526ffec8-6247-4576-9ce6-3eca4595ec65.png)

This has nothing to do with Visual Studio, because I get the same error when I try to add a migration using the ef6.exe command line tool. Obviously I can't run the "update database" command, because all the previous migrations have already been applied to the database and are visible in the __MigrationHistory table. So basically I'm stuck in limbo.

Any idea how to fix this?

**Comment by creativesuspects** [comment]
In my case it turned out that the value in the ContextKey column of the __MigrationHistory table was not correct. It should obviously contain the key for the DbContext, in my case 'EntityContext'. But instead it contained the name of the DbMigrationsConfiguration class: 'Application.Data.Migrations.Configuration'. This is the code for that class.

```
namespace Application.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using Application.Data.DataContext;

    internal sealed class Configuration : DbMigrationsConfiguration<EntityContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
            AutomaticMigrationDataLossAllowed = false;
            ContextKey = "EntityContext";
            MigrationsDirectory = @"Migrations";
        }

        protected override void Seed(EntityContext context)
        {
            //  This method will be called after migrating to the latest version.

            //  You can use the DbSet<T>.AddOrUpdate() helper extension method 
            //  to avoid creating duplicate seed data.
        }
    }
}
```

I was able to get the migrations working again by manually updating the values in the ContextKey column. Any idea why the name of DbMigrationsConfiguration class would be saved in the ContextKey column instead of the actual name of the DbContext?

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
