### ISSUE TITLE
Move designer to a separate repo

### ISSUE THREAD

**Issue by bricelam** [dotnet/ef6#694]
Given their different release cadences, it may make sense to move the EF6 tooling into a separate repository. This lets us avoid release branches where only some of the binaries ship.

**Comment by OlivierJullian** [comment]
Can you telle us where is now the EF6 tooling separate repository? Thank you!

**Comment by bricelam** [comment]
I think it builds from [the branches named MicroBuild](https://github.com/dotnet/ef6/branches/all?query=MicroBuild). @lajones would know the specifics.

**Comment by lajones** [comment]
@OlivierJullian We have not yet moved them to a separate repo. Also note, what we're referring to here is the EF6 Designer etc, not the command-line tools.

But assuming that's what you mean, at the moment the VS2017 builds from the 180702_MicroBuild_01 branch and VS2019 builds from 190313_Dev16_MicroBuild_07.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.

**Comment by bricelam** [comment]
We did this. It moved to the [dotnet/ef6tools](https://github.com/dotnet/ef6tools) repo.

**Comment by CZEMacLeod** [comment]
@bricelam Just had a quick look at that repo since I hadn't noticed it. 
Does it have a complete copy of the [EntityFramework](https://github.com/dotnet/ef6tools/tree/main/src/EntityFramework), [EntityFramework.SqlServer](https://github.com/dotnet/ef6tools/tree/main/src/EntityFramework.SqlServer), and [EntityFramework.SqlServerCompact](https://github.com/dotnet/ef6tools/tree/main/src/EntityFramework.SqlServerCompact) source code in it?
Should it not just use the packages, or perhaps include this repo as a submodule, otherwise it will be referencing stale code unless there is some mechanism to keep it up to date from this repo?

**Comment by bricelam** [comment]
Yes and yes. They're aware of this, and I believe they intend to address it as part of a bigger cleanup of their build infrastructure.
